### ISSUE TITLE
About the training data for the weights file

### ISSUE THREAD

**Issue by PES2g** [zhenngbolun/Learnbale_Bandpass_Filter#1]
As in your paper, there are two training dataset, TIP2018 datasets and LCDMoire. So i want to know which dataset is used to train the weight file provided in the readme ?

**Comment by zhenngbolun** [comment]
The pre-trained weights are for LCDMoire dataset.

**Comment by PES2g** [comment]
So could you provide the pretrained weights for TIP2018 ?

**Comment by zhenngbolun** [comment]
This weight file is now unavailable, because this file is in the Huawei's LAN, and I have no authority to put it on web.

**Comment by PES2g** [comment]
OK, Thanks for your reply.
