### ISSUE TITLE
The link of drive is not working.

### ISSUE THREAD

**Issue by BhavyaSoni31** [zhenngbolun/Learnbale_Bandpass_Filter#15]
The link for weights of drive is not working. [https://1drv.ms/u/s!ArU0YIIFiFuHilwyuwHZjSpvPUBz?e=iZ70Ga](https://1drv.ms/u/s!ArU0YIIFiFuHilwyuwHZjSpvPUBz?e=iZ70Ga)

**Comment by zhenngbolun** [comment]
The link is achievable. Maybe there is something wrong with your network
![image](https://user-images.githubusercontent.com/23093479/127999128-ba606df9-7b6c-421e-96f0-7e46da665970.png)
