### ISSUE TITLE
About the PSNR score on LCDMoire validation dataset

### ISSUE THREAD

**Issue by viengiaan** [zhenngbolun/Learnbale_Bandpass_Filter#2]
Hello,

We have tried to run your testing code on the LCDMoire validation dataset. And it only achieves 37.90 dB with "MBCNN_weights.h5". In the paper, the model tests on the LCDMoire performs  44.04 dB.

I wonder whether there are any problems or missing in the code so that it cannot reproduce the results the same as in the paper.

**Comment by zhenngbolun** [comment]
Thanks for you question.
This is because we set the "pre_block" to "enable=False". This is used for internal investigation in the paper.
Now we have set the "pre_block" to "enable=True".
You can view the latest updated "model.py".

**Comment by viengiaan** [comment]
Thank you for your reply.

We have just re-run the testing code, and the network reproduces the results the same as in the paper.
