### ISSUE TITLE
NameError: name 'adaptive_implicit_trans' is not defined

### ISSUE THREAD

**Issue by phexic** [zhenngbolun/Learnbale_Bandpass_Filter#4]
hi, I am trying to run main_multiscale.py, I get an error as "NameError: name 'adaptive_implicit_trans' is not defined". 
did i miss any configurations?
Traceback (most recent call last):
  File "main_multiscale.py", line 25, in <module>
    model = MBCNN(64,multi_output) #MBCNN-light: model = MBCNN(32,multi_output)
  File "/root/data/glusterfs_cv_04/11085439/code/demoire/Learnbale_Bandpass_Filter/model.py", line 78, in MBCNN
    t1 = pre_block(t1, d_list_a, True)
  File "/root/data/glusterfs_cv_04/11085439/code/demoire/Learnbale_Bandpass_Filter/model.py", line 43, in pre_block
    t = adaptive_implicit_trans()(t)
NameError: name 'adaptive_implicit_trans' is not defined

**Comment by zhenngbolun** [comment]
Thanks for your question. I have corrected this error.
Now you can update the 'core_layers.py' from the GitHub to solve this problem.

**Comment by phexic** [comment]
thanks

**Comment by phexic** [comment]
there are still some errors:

**Comment by phexic** [comment]
line 38 in core_layer.py also needs to be corrected

**Comment by zhenngbolun** [comment]
Thanks, I have fixed it.

**Comment by phexic** [comment]
will you public the code for training the model?

**Comment by zhenngbolun** [comment]
> will you public the code for training the model?

For next weeks, we have no plan to public the training code.
You can reference the details in our paper to train the MBCNN.

**Comment by phexic** [comment]
I see. Thank you.
