### ISSUE TITLE
LCDMoire Dataset

### ISSUE THREAD

**Issue by smiler96** [zhenngbolun/Learnbale_Bandpass_Filter#5]
Hi, thanks for releasing mbcnn test code publicly. 
And mbcnn performs well on the LCDMoire dataset which provided by AIM 2019. 
The paper "AIM 2019 Challenge on Image Demoireing: Dataset and Study" says the dataset was generated by the similar pipeline proposed by the paper "Demoireing of camera-captured screen images using deep convolutional neural network".
The dataset makes it important for the deep learning based demoireing mthod.
I've looked through both the above papers and got some question above the dataset generation method. 
I got confused about the two resampling processing, which respectively is LCD subpixels and Bayer CAF, listed in the dataset generation pipeline.
Could you please public the dataset generation method code? 
Or may we get further discussing about the dataset generation method if you know more about it?

**Comment by zhenngbolun** [comment]
You can discuss the details of LCDMoire dataset with Shanxin Yuan (the 2nd author).

**Comment by smiler96** [comment]
> You can discuss the details of LCDMoire dataset with Shanxin Yuan (the 2nd author).

got it, thanks.

**Comment by PrinceDouble** [comment]
> > You can discuss the details of LCDMoire dataset with Shanxin Yuan (the 2nd author).
> 
> got it, thanks.

兄弟，你有关于这个摩尔纹图片合成的代码吗？ 找了好久还是没有源码，如果有的话或者能生成差不多效果的方法，能够分享一下吗？多谢啦！！！邮箱1299150546@qq.com

**Comment by zsz0113** [comment]
> n

兄弟，你有关于这个摩尔纹图片合成的代码吗？ 找了好久还是没有源码，如果有的话或者能生成差不多效果的方法，能够分享一下吗？多谢啦！！！邮箱1054928323@qq.com

**Comment by smiler96** [comment]
> > n
> 
> 兄弟，你有关于这个摩尔纹图片合成的代码吗？ 找了好久还是没有源码，如果有的话或者能生成差不多效果的方法，能够分享一下吗？多谢啦！！！邮箱[1054928323@qq.com](mailto:1054928323@qq.com)

 没有复现出来

**Comment by zsz0113** [comment]
有差不多的版本代码可以供我参考一下嘛？
光看步骤，有点摸不清头绪。
谢谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhenngbolun/Learnbale_Bandpass_Filter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月22日(星期五) 下午3:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhenngbolun/Learnbale_Bandpass_Filter] LCDMoire Dataset (#5)





   
n
  
兄弟，你有关于这个摩尔纹图片合成的代码吗？ ***@***.***
  
没有复现出来
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tju-chengyijia** [comment]
> 

hi, can you share me the code?
my email: yijia_cheng@tju.edu.cn
thanks!

**Comment by tju-chengyijia** [comment]
> > You can discuss the details of LCDMoire dataset with Shanxin Yuan (the 2nd author).
> 
> got it, thanks.

hi, can you share me the code?
my email: [yijia_cheng@tju.edu.cn](mailto:yijia_cheng@tju.edu.cn)
thanks!

**Comment by Shawn-CodeDev** [comment]
Could you please share the data set with me? I haven't found it for a long time. My email address is gary_144@outlook.com. Thank you!

**Comment by LaplaceSong** [comment]
Could you please share the data set with me? I haven't found it for a long time. My email address is [2905782008@qq.com](mailto:2905782008@qq.com) Thank you!

**Comment by sjx-a** [comment]
can you share me the LCDMoire dataset?
my email: 2254770343@qq.com
thanks!

**Comment by Gtrees-w** [comment]
Could you please share the LCDMoire dataset with me? I haven't found it for a long time. My email address is [gsssssw@163.com](mailto:gsssssw@163.com) Thank you!

**Comment by Morgue-cc** [comment]
can you share me the LCDMoire dataset?
my email:2419707678@qq.com
thanks!

**Comment by xkainz00** [comment]
could you please also share the dataset with me xaver.kainz@check24.de ?
Many thanks,
Xaver

**Comment by nafe93** [comment]
can you share me the LCDMoire dataset?
my email: [nalkzir@hse.ru](mailto:nalkzir@hse.ru)
thanks!
